apiVersion: v1
kind: Service

metadata:
  namespace: monitoring
  name: service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
