# prometheus/deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment-prometheus
  namespace: monitoring
  labels:
    app: prometheus

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      restartPolicy: Always
      containers:
      - name: pod-prometheus
        image: prom/prometheus:v2.44.0
        ports:
        - containerPort: 9090
